# Generated by Django 3.2.7 on 2022-09-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'KeyWord',
                'verbose_name_plural': 'KeyWords',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='key_words',
        ),
        migrations.AddField(
            model_name='article',
            name='key_words',
            field=models.ManyToManyField(to='football.KeyWord'),
        ),
    ]
