# Generated by Django 3.2.7 on 2022-08-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_favorite_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='matchteam',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchteam',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='posttweet',
            options={'verbose_name': 'Post et Tweet', 'verbose_name_plural': 'Posts et Tweets'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchTeam',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
