# Generated by Django 3.2.7 on 2022-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20220930_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
