# Generated by Django 3.2.7 on 2022-11-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the article'),
        ),
    ]
